app/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash
from sqlalchemy import func
from . import login_manager

class User(db.Model,UserMixin):
	__tablename__='users'
	id=db.Column(db.Integer,primary_key=True)
	username=db.Column(db.String(255),unique=True)
	email=db.Column(db.String(255),unique=True)
	password=db.Column(db.String(255))
	posts = db.relationship('Post', backref='user', lazy='dynamic')
	comments = db.relationship('Comment', backref='user', lazy='dynamic')
	likes = db.relationship('Upvote', backref='user', lazy='dynamic')
	dislikes = db.relationship('Downvote', backref='user', lazy='dynamic')

	def verifypass(self,pass_check):
		return check_password_hash(self.password,pass_check)

	@property
	def passwd(self):
		raise AttributeError('You cannot read this!')

	@passwd.setter
	def passwd(self,passwd):
		self.password = generate_password_hash(passwd)

	def save(self):
		db.session.add(self)
		db.session.commit()
		
	def __repr__(self):
		return '<User %r>' % self.username

class Category(db.Model):
    __tablename__="categories"
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.String(255))

class Post(db.Model):
	__tablename__='posts'
	id=db.Column(db.Integer,primary_key=True)
	title=db.Column(db.String(255))
	text=db.Column(db.Text())
	user_id=db.Column(db.Integer, db.ForeignKey('users.id'))
	category=db.Column(db.String(255))
	created_at = db.Column(db.DateTime, index=True, default=func.now())
	updated_at = db.Column(db.DateTime, default=func.now())
	likes=db.relationship('Upvote', backref='post', lazy='dynamic')
	dislikes=db.relationship('Downvote', backref='post', lazy='dynamic')
	comments=db.relationship('Comment', backref='post', lazy='dynamic')

	def save(self):
		db.session.add(self)
		db.session.commit()

	def delete_(self):
		for items in self.likes.all()+self.dislikes.all()+self.comments.all():
			items.delete_()
		db.session.delete(self)
		db.session.commit()

class Comment(db.Model):
	__tablename__='comments'
	id=db.Column(db.Integer,primary_key=True)
	user_id=db.Column(db.Integer, db.ForeignKey('users.id'))
	post_id=db.Column(db.Integer, db.ForeignKey('posts.id'))
	text=db.Column(db.Text())
	created_at = db.Column(db.DateTime, index=True, default=func.now())
	updated_at = db.Column(db.DateTime, default=func.now())
	def save(self):
		db.session.add(self)
		db.session.commit()
	def delete_(self):
		db.session.delete(self)
		db.session.commit()

class Upvote(db.Model):
	__tablename__='upvotes'
	id=db.Column(db.Integer,primary_key=True)
	user_id=db.Column(db.Integer, db.ForeignKey('users.id'))
	post_id=db.Column(db.Integer, db.ForeignKey('posts.id'))
	def save(self):
		db.session.add(self)
		db.session.commit()
	def delete_(self):
		db.session.delete(self)
		db.session.commit()

class Downvote(db.Model):
	__tablename__='downvotes'
	id=db.Column(db.Integer,primary_key=True)
	user_id=db.Column(db.Integer, db.ForeignKey('users.id'))
	post_id=db.Column(db.Integer, db.ForeignKey('posts.id'))
	def save(self):
		db.session.add(self)
		db.session.commit()
	def delete_(self):
		db.session.delete(self)
		db.session.commit()

@login_manager.user_loader
def usergetter(uid):
	return User.query.get(uid)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,SelectField,TextAreaField
from wtforms.validators import Required,Length

class PitchForm(FlaskForm):
    CATEGORIES=[('pickup lines', 'pickup lines'), ('interview pitch', 'interview pitch'), ('product pitch', 'product pitch'), ('promotion pitch', 'promotion pitch')]
    title=StringField('Title', validators=[Required(), Length(1, 255)])
    category=SelectField("categories",choices=CATEGORIES)
    pitch=TextAreaField("Pitch",validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment=TextAreaField("",validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db=SQLAlchemy()
login_manager=LoginManager()
login_manager.session_protection="strong"
login_manager.login_view="auth.login"

def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config_options[config_name])
    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    # register blueprints
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint,url_prefix="/auth")
    return app

app/main/__init__.py
from flask import Blueprint

main=Blueprint("main",__name__)
from . import views
from . import errors

app/main/views.py
from flask import render_template,redirect, url_for
from flask_login import current_user,login_required
from . import main
from .forms import PitchForm,CommentForm
from app.models import Post,Comment,Upvote,Downvote

@main.route("/",methods=["GET","POST"])
def index():
    categories=["pickup lines", "interview pitch", "product pitch", "promotion pitch"]
    return render_template('index.html',categories=categories)

@main.route("/pitches/<string:category>")
def pitches(category):
    pitches=list(Post.query.filter_by(category=category))
    return render_template("./main/pitches.html",pitches=pitches)

@main.route("/pitch/<int:pitch_id>",methods=["GET","POST"])
def pitch(pitch_id):
    comment_form=CommentForm()
    if comment_form.validate_on_submit():
        comment=Comment(
            user_id=current_user.id,
            post_id=pitch_id,
            text=comment_form.comment.data
        )
        comment.save()
    comments=Comment.query.filter_by(post_id=pitch_id)
    pitch=Post.query.filter_by(id=pitch_id).first()
    context={"pitch":pitch,"comments":comments,"comment_form":comment_form}
    return render_template("./main/pitch.html",**context)

@main.route("/add_pitch",methods=["GET","POST"])
@login_required
def add_pitch():
    pitch_form=PitchForm()
    if pitch_form.validate_on_submit():
        print(pitch_form.category.data)
        pitch=Post(
            title=pitch_form.title.data,
            text=pitch_form.pitch.data,
            category=pitch_form.category.data,
            user_id=current_user.id,
        )
        pitch.save()
        return redirect(url_for("main.index"))
    return render_template('./main/add_pitch.html',pitch_form=pitch_form)


@main.route("/pitch/upvote/<int:pitch_id>")
@login_required
def upvote(pitch_id):
    upvote_=Upvote.query.filter_by(user_id=current_user.id,post_id=pitch_id).first()
    if not upvote_:
        upvote_=Upvote(user_id=current_user.id,post_id=pitch_id)
        upvote_.save()
    else:
        upvote_.delete_()
    return redirect(url_for("main.pitch",pitch_id=pitch_id))


@main.route("/pitch/downvote/<int:pitch_id>")
@login_required
def downvote(pitch_id):
    downvote_=Downvote.query.filter_by(user_id=current_user.id,post_id=pitch_id).first()
    if not downvote_:
        downvote_=Downvote(user_id=current_user.id,post_id=pitch_id)
        downvote_.save()
    else:
        downvote_.delete_()
    return redirect(url_for("main.pitch",pitch_id=pitch_id))

app/templates/base.html
{% extends "bootstrap/base.html" %}
<head>
    {% block head %}
        {{super()}}
        <title> {% if title %} {{title}} {% else %} Pitches {% endif %} </title>
    {% endblock %}

    {% block styles %}
        {{super()}}
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% endblock %}
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="/">One Minute Pitch</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav ml-auto">
                {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.profile')}}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% endblock %}

    {% block content %}
    
    {% endblock %}
</body>

app/templates/index.html
{% extends "./base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container" style="margin-top:30px">
        <div class="page-header">
            <h3 >Select a pitch category</h3>
        </div>
        {% if current_user.is_authenticated %}
        <div class="container">
            <a class="btn btn-primary" href="{{url_for('main.add_pitch')}}">+ Add Pitch</a>
        </div>
        {% endif %}
        <div class="list-group" style="margin-top:30px">
            {% for category in categories %}
            <a href="/pitches/{{category}}" class="list-group-item list-group-item-action">{{category}}</a>
            {% endfor %}
        </div>

    </div>

{% endblock %}

app/templates/main/add_pitch.html
{% extends "./base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    {% if current_user.is_authenticated %}
    <div class="container" style="margin-top:30px">
        <h2>Pitch Form</h2>
        {% if error %}
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                {{error}}
            </div>
        {% endif %}
        {{ wtf.quick_form(pitch_form) }}
    </div>
    {% endif %}
{% endblock %}

app/templates/main/pitch.html
{% extends "./base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container" style="margin-top:30px">
        {% if pitch %}
        <div class="card gedf-card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="ml-2">
                            <div class="h7 text-muted">{{pitch.title}}</div>
                        </div>
                    </div>
                </div>
    
            </div>
            <div class="card-body">
                <div class="text-muted h7 mb-2"> 
                    <p>Posted on {{pitch.created_at.date()}}</p>
                    <p>By {{pitch.user.username}}</p>
                </div>
                <p class="card-text">
                    {{pitch.text}}
                </p>
                <div>
                    <span class="badge badge-primary">Upvotes: {{pitch.likes.count()}}</span>
                    <span class="badge badge-primary">Downvotes: {{pitch.dislikes.count()}}</span>
                </div>
            </div>
            {% if current_user.is_authenticated %}
            <div class="card-footer">
                <a href="/pitch/upvote/{{pitch.id}}" class="card-link">upvote</a>
                <a href="/pitch/downvote/{{pitch.id}}" class="card-link">downvote</a>
            </div>
            {% endif %}
        </div>
        {% endif %}
    </div>
    {% if current_user.is_authenticated %}
    <div class="container" style="margin-top:30px">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                {{error}}
            </div>
        {% endif %}
        <div class="card">
            <div class="card-header">
                Comment
            </div>
            <div class="body">
                {{ wtf.quick_form(comment_form) }}
            </div>
        </div>
    </div>
    {% endif %}
    <div class="container" style="margin-top:30px">
        <h4>Comments</h4>
        {% for comment in comments %}
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Posted by {{comment.user.username}} on {{comment.created_at.date()}}
                    </div>
                    <div class="card-body">{{comment.text}}</div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
{% endblock %}

app/templates/main/pitches.html
{% extends "./base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container" style="margin-top:30px">

        <div class="page-header">
            <h3>Pitches</h3>
        </div>
        <div class="card-columns">
            {% if pitches %}
            {% for pitch in pitches %}
            <div class="card">
                <div class="card-header">
                    <a href="/pitch/{{pitch.id}}">
                        {{pitch.title}}
                    </a>
                </div>
                <div class="card-body">{{pitch.text[:32]}}</div>
                <div class="card-footer">
                    <p>By {{pitch.user.username}}</p>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h4>No pitch in this category yet !!</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}